version: '3.8'

services:
  mongo:
    image: mongo:latest
    deploy:
      replicas: 1
      resources:
        limits:
          memory: 512M
    volumes:
      - mongodb-data:/data/db
    ports:
      - "27017:27017"
    networks:
      - mongo-network

volumes:
  mongodb-data:

networks:
  mongo-network:
    driver: overlay
