apiVersion: v1
kind: ConfigMap
metadata:
  name: my-configmap
  namespace: shira
data:
  facts: |
    - I went on a security mission in Yeruham.
    - I love k8s.
    - I still have a worker's allowance at the place where I worked before the army.
  age: "18"  
